
import numpy as np

from langchain_openai import OpenAIEmbeddings,ChatOpenAI
from vectordb.vector_db_manager import VectorDBManager
from pinecone import Pinecone, IndexModel, ServerlessSpec

from markdown_it import MarkdownIt  
from markdown_it.tree import SyntaxTreeNode

from io import BytesIO
import pymupdf.layout
import pymupdf4llm
import pymupdf


from pdf_pipeline.etree import EmbedTreeNode 
from pdf_pipeline.gdoctree import GdocTreeNode
from googledoc.googledoc import GoogleDocsEditor

from dotenv import load_dotenv
import os
import time
load_dotenv(os.path.join(os.environ.get('LAMBDA_TASK_ROOT', ''), '.env'))



class superdoc():
    
    #Clean up init
    def __init__(self,DOCUMENT_ID:str|None,COURSE_ID:str,index_name='sdtest1'):
        self.DOCUMENT_ID = DOCUMENT_ID
        self.COURSE_ID = COURSE_ID
        self.docs_editor = GoogleDocsEditor()
        if DOCUMENT_ID is None: 
            self.DOCUMENT_ID = self.docs_editor.create_google_doc(name=COURSE_ID).get('documentId')

        self.db = VectorDBManager(pc=Pinecone(os.environ.get("PINECONE_API_KEY")))
        self.db.initVectorStore(index_name=index_name, embedding=OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")))
        
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.emb_model =OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")) 
    
    @staticmethod
    def pdf_to_syntree(stream:BytesIO) -> SyntaxTreeNode:
        doc = pymupdf.open(stream=stream)
        markdown = pymupdf4llm.to_markdown(doc)
        mdit = MarkdownIt()
        md = mdit.parse(markdown)
        return SyntaxTreeNode(md)
    
    def stree_to_etree(self,stree:SyntaxTreeNode):
        print("Building Semantic Tree...")
        root = EmbedTreeNode._init_tree(root_node=stree, emb_model=self.emb_model)
        EmbedTreeNode._embed_tree_(root)
        EmbedTreeNode._calc_block_len(root)
        return root

        


    def merge_pdf_hierarchical(self, stream: BytesIO):
        """
        New tree-based merge functionality that respects document hierarchy 
        and handles custom heading injection.
        """
        print(f"--- Starting Hierarchical Merge for Doc: {self.DOCUMENT_ID} ---")
        
        # 1. Convert PDF to Syntax Tree (Markdown-it structure)
        # Note: Ensure pdf_to_syntree is available in your scope
        start_time = time.perf_counter()
        synt_tree = self.pdf_to_syntree(stream=stream) 
        
        # 2. Build the Semantic EmbedTree and calculate embeddings
        # This populates node.emb and node.mean_emb (as native Python lists)
        root = self.stree_to_etree(stree=synt_tree)
        
        # 3. Fetch existing headings from Pinecone for this course/doc
        # This allows the tree to find where this new PDF "fits" into existing topics
        existing_headings = self.db.get_all_headings_for_doc(
            course_id=self.COURSE_ID, 
            superdoc_id=self.DOCUMENT_ID
        )
        
        # 4. Inject Custom Headings and detect "Stragglers"
        # new_cust_nodes: Brand new headings generated by LLM for orphaned content
        # all_cust_nodes: Total set of custom nodes (existing + new) to be rendered
        new_cust_nodes, all_cust_nodes = root.reconcile_structure(headings=existing_headings)
        
        # 5. Sync new structural nodes to Vector DB
        # We only append the NEWLY generated headings so we don't duplicate existing ones
        if new_cust_nodes:
            print(f"Syncing {len(new_cust_nodes)} new custom headings to Pinecone...")
            self.db.append_documents(
                e_branches=new_cust_nodes, 
                course_id=self.COURSE_ID, 
                superdoc_id=self.DOCUMENT_ID
            )

        # 6. Render to Google Docs
        # This uses the specialized hierarchical renderer
        print(f"Rendering {len(all_cust_nodes)} custom branches to Google Doc...")
        render_start = time.perf_counter()
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.docs_editor.mutate_named_ranges(document_id=self.DOCUMENT_ID)
        # This method handles named ranges and structural formatting
        self.docs_editor.render_etree_custom_nodes(
            superdoc_id=self.DOCUMENT_ID, 
            all_cust_nodes=all_cust_nodes
        )
        
        end_time = time.perf_counter()
        print(f"Total Merge Process completed in: {(end_time - start_time):.2f}s")
        print(f"Google Doc Render took: {(end_time - render_start):.2f}s")
   
    def delete_heading(self,old_heading:str): 
        self.docs_editor.delete_heading(old_heading=old_heading)
        self.db.remove_vectordb_heading(heading=old_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)
    
    def create_heading(self,new_heading:str):
        self.docs_editor.create_heading(new_heading=new_heading)
        self.db.create_vectordb_heading(heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)

    '''Updates old_heading in both google docs and vectorDb'''
    def update_heading(self,old_heading:str,new_heading:str):
        #update googledoc heading named range
        self.docs_editor.update_heading(old_heading=old_heading,new_heading=new_heading)
        self.db.replace_vectordb_heading_with_text(old_heading=old_heading,new_heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)

    def create_document(self,name:str,course_id): 
        return self.docs_editor.create_google_doc(name=name,courseid=course_id)

    def get_docids(self, course_id: str) -> dict: 
        # 1. Get the list of document IDs (assuming this returns a list)
        document_ids = self.docs_editor.get_docids(courseid=course_id)
        
        # 2. Initialize the dictionary
        docs_map = {}
        
        for docid in document_ids:
            # 3. Get the document structure/metadata
            # Usually, the title/name is found in the 'title' field of the doc object
            doc_structure = self.docs_editor.get_document_structure(docid)
            
            # Extract the name (adjust key based on your get_document_structure return type)
            doc_name = doc_structure.get('title', 'Untitled Document')
            
            # 4. Map the Name to the ID
            docs_map[doc_name] = docid
            
        return docs_map
            
    
    
if __name__ == '__main__': 
    with open("files/Chloroplasts_w_citations.pdf", "rb") as f:
        pdf_bytes = f.read()
    strm = BytesIO(pdf_bytes)

    sd = superdoc(DOCUMENT_ID='13OiEdtje4wMZGT1LEfVmj3RmAeR1BchUF6eZBaICH8w',COURSE_ID="RHET1302")
    sd.merge_pdf_hierarchical(stream=strm)
    #sd.merge_pdf()
   # sd.update_heading(old_heading="Introduction",new_heading="GoofyGoober")
    #sd.create_heading(new_heading="Trump giving Kirk to Bubba")
