
import numpy as np

from langchain_openai import OpenAIEmbeddings,ChatOpenAI
from vectordb.vector_db_manager import VectorDBManager
from pinecone import Pinecone, IndexModel, ServerlessSpec

from markdown_it import MarkdownIt  
from markdown_it.tree import SyntaxTreeNode

from io import BytesIO
import pymupdf.layout
import pymupdf4llm
import pymupdf


from pdf_pipeline.etree import EmbedTreeNode 
from pdf_pipeline.gdoctree import GdocTreeNode
from googledoc.googledoc import GoogleDocsEditor
from lexical.lexical_algs import extract_text_similarity_jaccard
from dotenv import load_dotenv
import os
import time
load_dotenv(os.path.join(os.environ.get('LAMBDA_TASK_ROOT', ''), '.env'))



class superdoc():
    #Clean up init
    def __init__(self,DOCUMENT_ID:str|None,COURSE_ID:str,index_name=os.getenv("PINECONE_INDEX", "superdoc-headings")):
        self.DOCUMENT_ID = DOCUMENT_ID
        self.COURSE_ID = COURSE_ID
        self.docs_editor = GoogleDocsEditor()
        if DOCUMENT_ID is None: 
            self.DOCUMENT_ID = self.docs_editor.create_google_doc(name=COURSE_ID).get('documentId')

        self.db = VectorDBManager(pc=Pinecone(os.environ.get("PINECONE_API_KEY")))
        self.db.initVectorStore(index_name=index_name, embedding=OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")))
        
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.emb_model =OpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY")) 
    
    @staticmethod
    def pdf_to_syntree(stream:BytesIO) -> SyntaxTreeNode:
        doc = pymupdf.open(stream=stream)
        markdown = pymupdf4llm.to_markdown(doc)
        mdit = MarkdownIt()
        md = mdit.parse(markdown)
        return SyntaxTreeNode(md)
    
    @staticmethod
    def stree_to_etree(self,stree:SyntaxTreeNode) -> EmbedTreeNode:
        print("Building Semantic Tree...")
        root = EmbedTreeNode._init_tree(root_node=stree, emb_model=self.emb_model)
        EmbedTreeNode._embed_tree_(root)
        EmbedTreeNode._calc_block_len(root)
        return root

        
    '''
    
        Main merging algorithm

    '''

    def merge_pdf_hierarchical(self, stream: BytesIO):
        """
        New tree-based merge functionality that respects document hierarchy 
        and handles custom heading injection.
        """
        print(f"--- Starting Hierarchical Merge for Doc: {self.DOCUMENT_ID} ---")
        
        # 1. Convert PDF to Syntax Tree (Markdown-it structure)
        # Note: Ensure pdf_to_syntree is available in your scope
        start_time = time.perf_counter()
        synt_tree = self.pdf_to_syntree(stream=stream) 
        
        # 2. Build the Semantic EmbedTree and calculate embeddings
        # This populates node.emb and node.mean_emb (as native Python lists)
        root = self.stree_to_etree(stree=synt_tree)
        
        # 3. Fetch existing headings from Pinecone for this course/doc
        # This allows the tree to find where this new PDF "fits" into existing topics
        existing_headings = self.db.get_all_headings_for_doc(
            course_id=self.COURSE_ID, 
            superdoc_id=self.DOCUMENT_ID
        )
        
        # 4. Inject Custom Headings and detect "Stragglers"
        # new_cust_nodes: Brand new headings generated by LLM for orphaned content
        # all_cust_nodes: Total set of custom nodes (existing + new) to be rendered
        new_cust_nodes, all_cust_nodes = root.reconcile_structure(headings=existing_headings)
        
        #Lexical Redundnacy check
        if all_cust_nodes:
            print("Running Lexical Redundancy Check on Tree Branches...")
            self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)  # <-- fresh doc obj
            
            for branch in all_cust_nodes:
                if hasattr(branch, 'children') and branch.children:
                    heading_text = getattr(branch, 'content', '').strip()
                    print(f"Checking {len(branch.children)} nodes under: '{heading_text}'")
                    branch.children = self.lexical_redundancyCheck(
                        nodes=branch.children,
                        heading=heading_text  # <-- pass heading explicitly
                    )
            
            # Remove branches that are now empty after pruning
            all_cust_nodes = [b for b in all_cust_nodes if len(getattr(b, 'children', [])) > 0]


        # 5. Sync new structural nodes to Vector DB
        # We only append the NEWLY generated headings so we don't duplicate existing ones
        if new_cust_nodes:
            print(f"Syncing {len(new_cust_nodes)} new custom headings to Pinecone...")
            self.db.append_documents(
                e_branches=new_cust_nodes, 
                course_id=self.COURSE_ID, 
                superdoc_id=self.DOCUMENT_ID
            )

        # 6. Render to Google Docs
        # This uses the specialized hierarchical renderer
        print(f"Rendering {len(all_cust_nodes)} custom branches to Google Doc...")
        render_start = time.perf_counter()
        self.docs_editor.get_document_structure(document_id=self.DOCUMENT_ID)
        self.docs_editor.mutate_named_ranges(document_id=self.DOCUMENT_ID)
        # This method handles named ranges and structural formatting
        self.docs_editor.render_etree_custom_nodes(
            superdoc_id=self.DOCUMENT_ID, 
            all_cust_nodes=all_cust_nodes
        )
        
        end_time = time.perf_counter()
        print(f"Total Merge Process completed in: {(end_time - start_time):.2f}s")
        print(f"Google Doc Render took: {(end_time - render_start):.2f}s")

    '''
    
        Heading management
    
    '''

    def delete_heading(self,old_heading:str): 
        self.docs_editor.delete_heading(old_heading=old_heading)
        self.db.remove_vectordb_heading(heading=old_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)
    
    def create_heading(self,new_heading:str):
        self.docs_editor.create_heading(new_heading=new_heading)
        self.db.create_vectordb_heading(heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)

    def update_heading(self,old_heading:str,new_heading:str):
        '''Updates old_heading in both google docs and vectorDb'''

        #update googledoc heading named range
        self.docs_editor.update_heading(old_heading=old_heading,new_heading=new_heading)
        self.db.replace_vectordb_heading_with_text(old_heading=old_heading,new_heading_text=new_heading,course_id=self.COURSE_ID,superdoc_id=self.DOCUMENT_ID)



    def fix_heading_update(self): 
        """
        Synchronizes the document structure from Google Docs with Pinecone.
        Finds changed or deleted headings and processes them in  batches
        for both OpenAI API calls and Pinecone vector operations.
        """
        #Fetch current live doc structure and existing DB headings
        self.docs_editor.get_document_structure() 
        doc_headings = self.get_all_headings_for_doc(
            course_id=self.COURSE_ID, 
            superdoc_id=self.DOCUMENT_ID
        )

        delete_ids = []
        headings_to_embed = []
        
        def chunk_list(lst, n):
            for i in range(0, len(lst), n):
                yield lst[i:i + n]

        #Extract and analyze document content
        for db_entry in doc_headings: 
            heading_text = db_entry.get("heading")
            vector_id = db_entry.get("id")
            
            content_under_heading = self.get_text_in_range_from_doc_obj(heading_text)
            
            # Case 1: Heading or its content no longer exists in the document
            if not content_under_heading: 
                delete_ids.append(vector_id)
                continue
                  
            # Case 2: Content exists, but the literal "Heading:" prefix has changed
            prefix_target = f"{heading_text}:"
            if prefix_target not in content_under_heading: 
                delete_ids.append(vector_id)
                
                parts = content_under_heading.split(":", 1)
                potential_new_heading = parts[0].strip()
                
                if potential_new_heading:
                    # Queue the text for bulk embedding instead of querying immediately
                    headings_to_embed.append(potential_new_heading)

        vectors_to_upsert = []

        # Batch Query OpenAI for all queued headings
        if headings_to_embed:
            print(f"Batch embedding {len(headings_to_embed)} headings via OpenAI...")
            
            # OpenAI has limits on massive batch arrays, chunking at 500.
            for text_chunk in chunk_list(headings_to_embed, 500):
                # embed_documents takes a List[str] and returns a List[List[float]]
                embedded_vectors = self.emb_model.embed_documents(text_chunk)
                
                # Map them back together
                for text, vector in zip(text_chunk, embedded_vectors):
                    vectors_to_upsert.append({
                        "id": self.generate_timestamp_id(self.COURSE_ID),
                        "values": vector,
                        "metadata": {
                            "superdoc": self.DOCUMENT_ID,
                            "heading": text,
                        }
                    })

        # Execute Pinecone operations with a strict limit of 1,000 per request
        index = self.pc.Index(self.index_name)
        PINECONE_BATCH_LIMIT = 1000
        
        # Batch Delete
        if delete_ids:
            print(f"Processing {len(delete_ids)} total deletions in Pinecone...")
            for chunk in chunk_list(delete_ids, PINECONE_BATCH_LIMIT):
                print(f"Deleting chunk of {len(chunk)} vectors...")
                index.delete(ids=chunk, namespace=self.COURSE_ID)

        # Batch Upsert
        if vectors_to_upsert:
            print(f"Processing {len(vectors_to_upsert)} total upserts in Pinecone...")
            for chunk in chunk_list(vectors_to_upsert, PINECONE_BATCH_LIMIT):
                print(f"Upserting chunk of {len(chunk)} vectors...")
                index.upsert(vectors=chunk, namespace=self.COURSE_ID)
            
        print("Superdoc synchronization complete.")
                 

    def fix_new_content(self): 
        ''' 
            Get Document structure,
            detect skips(make new method in googledoceditor)
            
            new_vector_list = []
            create_heading_list = []           
            
            for each (start,end) in skips: 
                text = get_doc_text(start,end) 
                if(text and utf-text-len(text)>30): 
                    new_heading = generate_heading(text) 
                    create_heading_list.append(new_heading,start,end)
                    new_vector_list.append(new_heading) 

            batch update create_heading_list 
            batch update new_vector_list
        
        '''
        pass


    '''
    
        Google Doc creation and fetching
    
    '''


    def create_document(self,name:str,course_id): 
        return self.docs_editor.create_google_doc(name=name,courseid=course_id)



    def get_docids(self, course_id: str) -> dict: 
        # 1. Get the list of document IDs (assuming this returns a list)
        document_ids = self.docs_editor.get_docids(courseid=course_id)
        
        # 2. Initialize the dictionary
        docs_map = {}
        
        for docid in document_ids:
            # 3. Get the document structure/metadata
            # Usually, the title/name is found in the 'title' field of the doc object
            doc_structure = self.docs_editor.get_document_structure(docid)
            
            # Extract the name (adjust key based on your get_document_structure return type)
            doc_name = doc_structure.get('title', 'Untitled Document')
            
            # 4. Map the Name to the ID
            docs_map[doc_name] = docid
            
        return docs_map
    

    '''

        Lexical Redundancy

    '''
    
    def lexical_redundancyCheck(self, nodes: list, heading: str):
        print(f"\n[DEBUG] Starting Check for {len(nodes)} nodes under '{heading}'")
        
        pruned_tree = []
        LEXICAL_CHECK_CONSTANT = 0.7

        raw_doc_text = self.docs_editor.get_text_in_range_from_doc_obj(heading)
        existing_lines = [line.strip() for line in (raw_doc_text or "").split("\n") if line.strip()]
        print(f"  [CACHE] {len(existing_lines)} lines in GDoc under '{heading}'")

        for i, node in enumerate(nodes):
            node_text = self._extract_leaf_text(node)  # ← clean text from content attr

            if not node_text:
                print(f"  [NODE {i}] SKIP: No text found.")
                pruned_tree.append(node)
                continue

            is_redundant = False
            highest_score = 0

            for line in existing_lines:
                score = extract_text_similarity_jaccard(node_text, line)
                if score > highest_score:
                    highest_score = score
                if score >= LEXICAL_CHECK_CONSTANT:
                    is_redundant = True
                    break

            if not is_redundant:
                pruned_tree.append(node)
                print(f"  [KEEP]  '{node_text[:60]}' (max sim: {highest_score:.2f})")
            else:
                print(f"  [PRUNE] '{node_text[:60]}' (score: {highest_score:.2f})")

        print(f"[DEBUG] Done. Kept {len(pruned_tree)}/{len(nodes)}\n")
        return pruned_tree


    def _extract_leaf_text(self, node) -> str:
        """Walk down the tree until we find a node with actual content."""
        content = node.content.strip() if node.content else ""
        if content:
            return content
        for child in node.children:
            result = self._extract_leaf_text(child)
            if result:
                return result
        return ""
    
if __name__ == '__main__': 
    with open("files/Chloroplasts 1.pdf", "rb") as f:
        pdf_bytes = f.read()
    strm = BytesIO(pdf_bytes)

    sd = superdoc(DOCUMENT_ID='13OiEdtje4wMZGT1LEfVmj3RmAeR1BchUF6eZBaICH8w',COURSE_ID="RHET1302")
    #sd.merge_pdf_hierarchical(stream=strm)
    sd.create_document(name="Hellow",course_id="RHET1302")
    #sd.merge_pdf()
   # sd.update_heading(old_heading="Introduction",new_heading="GoofyGoober")
    #sd.create_heading(new_heading="Trump giving Kirk to Bubba")
